### PR TITLE
[SPEC-111] use the arup-group speckle admin

### PR DESCRIPTION
**Pull request by peterjgrainger**
Use the forked version of speckle admin rather than the speckleworks version

### CODE REVIEW

**Review by thatfleminggent — CHANGES_REQUESTED** [review]
I'm sure we discussed this and I said I wanted to avoid making Arup-specific changes to this role (as I want to eventually make this OSS / public)

Rejecting this pull request.

I would consider adding a role var to "pick a flavour" (be it arup-group or speckleserver or your-github-hosted-fork-here) but hard coding an internal one into the role is tres uncool for reasons previously outlined.

**Comment by daviddekoning** [comment]
@peterjgrainger I thought this role was copied over into the other repo and so we didn't have to make any changes here?

@thatfleminggent if you like, I would be happy to have a chat sometime about how we are developing Speckle within Arup, and how we are interacting with the upstream team.

**Comment by peterjgrainger** [comment]
@thatfleminggent that's fair. Will be easier to switch back to speckworks when we are done. I'll make it a variable. Would rather not make a fork if we don't have to. 

@daviddekoning there is already a copy but I update that from here if @thatfleminggent makes any alterations

**Comment by thatfleminggent** [comment]
@peterjgrainger the "flavour" var is honestly the more flexible option and is trivially easy. If you don't get time I can make this change directly. You can then flick between arup-group/speckleworks/jims-speckleservers etc etc at will.

(Making the url itself a var would also work but I've yet to see a non-Github-hosted fork. Yet. :P)

@daviddekoning I'm sure we've had this conversation before and I'm aware of how speckle is being developed in house (I may not be chatty on teams but I am in most of the relevant channels and paying attention, I'm also on SW's discourse forum).

My intention with this role is to make it generic / general purpose enough to be used by not just Arup but the wider Speckle community, and it's my intent to get it open-sourced (I gave Dimitrie my word that I'd do it, and it would cut the number of install support questions alongside promoting it's use :D)

Hence I've already explained to contributors that Arup-only "features" or hardcoding paths to point to "arup-group" URLs should not be pushed here, and I would reject PRs / revert changes that did so.

Insofar as keeping arup-specific copies - of course fine with me, ideally diffs should be fairly small (and hopefully getting smaller). The role is fairly mature now so I don't see much change going forward. In an Ideal Future(tm) you can pull direct from Galaxy and only keep playbooks.

**Pull request closed without merging**
